### ISSUE TITLE
SLOTS Are Being Reported Inaccurately

### ISSUE THREAD

**Issue by K2IE** [kc1awv/hbmonitor3#2]
Comparing with the behavior of hbmonitor, if hblink.cfg defines a Master resource configured with SLOTS: 3, display should be BOTH.  However, it currently displays as DMO.

For Homebrew Peers, hbmonitor used to report the actual linked timeslot (1, 2 or BOTH).  Now the slots are also reported as DMO.

Fix being tested now and will be sumitted as a pull request.

**Comment by kc1awv** [comment]
Will merge from PR #4
