### ISSUE TITLE
Frequency of all zeros supposed to show as N/A

### ISSUE THREAD

**Issue by K2IE** [kc1awv/hbmonitor3#3]
Frequencies of all zeros are showing up rather than N/A as in the python2 version.
Fix being tested now and will be sumitted as a pull request.

**Comment by kc1awv** [comment]
This is due to the bytes object requirements of Python 3, if I recall correctly. The port from Python 2 to Python 3 was just a quick-and-dirty solution to start improvements from because of the Python 2 EOL.  I'll wait for your PR.

**Comment by K2IE** [comment]
Yes, that was exactly it.  I have it up and running now with the changes and it looks identical to how it looked under python2.  Thanks for getting this effort underway.

Dan (K2IE, ex-K2DLS)

**Comment by kc1awv** [comment]
Great, and thank you for the help. I'm just leaving the office now and will merge the PR when I get back home.

**Comment by kc1awv** [comment]
Merged PR #4
